rm(list = ls())

setwd("/home/lv999/Dropbox/Github/SurvivalAnalysis/Distributions")


source("colorPalette.R")

### Distributions
source("alphaDistribution.R")
source("arcsineDistribution.R")
source("betaDistribution.R")
source("Birnbaum-SaundersDistribution.R")
source("BurrDistribution.R")
source("CauchyDistribution.R")
source("chiDistribution.R")
source("chisquareDistribution.R")
source("cosineDistribution.R")
source("Dhillon's1Distribution.R")
source("Dhillon's2Distribution.R")
source("doubleWeibullDistribution.R")
source("exponentialDistribution.R")
source("exponentialDistributionwithLocationParameter.R")
source("extremeValueDistribution_1(GumbelMaxDistribution).R")
source("extremeValueDistribution_1(GumbelMinDistribution).R")
source("extremeValueDistribution_2(FrechetDistribution).R")
source("extremeValueDistribution_2(FrechetDistributionwithLocationParameter).R")
source("FDistribution.R")
source("GammaDistributionwith2Parameters.R")
source("GammaDistributionwith3Parameters.R")
source("generalizedLomaxDistribution.R")
source("GompertzDistribution.R")
source("GompertzMakehamDistribution.R")
source("halfCauchyDistribution.R")
source("halfLogisticDistribution.R")
source("halfNormalDistribution.R")
source("hjorthDistribution.R")
source("hyperbolicSecantDistribution.R")
source("inverseNormalDistribution.R")
source("inverseRayleighDistribution.R")
source("inverseWeibullDistribution.R")
source("laplaceDistribution.R")
source("linearHazardRateDistribution.R")
source("logisticDistribution.R")
source("logLogisticDistribution.R")
source("lognormalDistribution.R")
source("logWeibullDistribution.R")
source("lomaxDistribution.R")
source("makehamDistribution.R")
source("muthDistribution.R")
source("normalDistribution.R")
source("parabolicInvertedUshapedDistribution.R")
source("parabolicUshapedDistribution.R")
source("paretoDistributionoftheFirstKind.R")
source("powerDistribution.R")
source("raisedCosineDistribution.R")
source("rayleighDistribution.R")
source("reflectedExponentialDistribution.R")
source("reflectedWeibullDistribution.R")
source("semiEllipticalDistribution.R")
source("tDistribution.R")
source("teisserDistribution.R")
source("uniformDistribution.R")
source("WeibullDistributionwith2Parameters.R")
source("WeibullDistributionwith3Parameters.R")
source("_exponentiatedExponentialDistribution.R")
source("_generalizedExponentialGeometricDistribution.R")
source("_generalizedGammaDistribution.R")
source("_generalizedLinearHazardRateDistribution.R")
source("_generalizedLogisticDistribution.R")
source("_generalizedRayleighDistribution.R")
source("_logGammaDistribution.R")
source("_logLaplaceDistribution.R")
source("_lognormalDistributionwithLowerThreshold.R")
source("_lognormalDistributionwithUpperThreshold.R")
source("_Maxwell-BoltzmannDistribution.R")
source("_TriangularDistribution.R")
source("_trimmedNormalDistribution.R")
source("_VshapedDistribution.R")



source("ksTest.R")
res = ksTest(rnorm(1000), parameterLen=10)